name: CI/CD Pipeline

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    if: "!startsWith(github.ref, 'refs/tags/')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test with Maven
        run: mvn clean compile test -Dkeycloak.version=26.2.5

  build-and-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-24.04
    # capture the tag (e.g. "1.0.0") into an env var
    env:
      RELEASE_NAME: ${{ github.ref_name }}
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v5

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Build with Maven
        run: mvn clean package -Dkeycloak.version=26.2.5

      - name: Rename JAR to include release name
        run: |
          # assumes your built jar is the only .jar in target/
          ORIGINAL_JAR=$(ls target/*.jar)
          mv "$ORIGINAL_JAR" "target/keycloak-pii-data-encryption-${RELEASE_NAME}.jar"

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: pii-encryption-provider
          path: target/keycloak-pii-data-encryption-${RELEASE_NAME}.jar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/keycloak-pii-data-encryption-${RELEASE_NAME}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
