name: CI/CD Pipeline

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    if: "!startsWith(github.ref, 'refs/tags/')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test with Maven
        run: mvn clean compile test -Dkeycloak.version=$KEYCLOAK_VERSION
        env:
          KEYCLOAK_VERSION: ${{ env.KEYCLOAK_VERSION }}

  build-and-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v5

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Build with Maven
        run: |
          mvn clean package -Dkeycloak.version=$KEYCLOAK_VERSION -Drevision=${GITHUB_REF_SLUG:1}
        env:
          KEYCLOAK_VERSION: ${{ env.KEYCLOAK_VERSION }}

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: pii-encryption-provider
          path: target/*.jar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
